name: Test

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    container:
      image: mikaak/elixir:1.13-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{github.ref}}-deps-build-cache
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Install Rebar & Hex
        run: mix local.hex --force --if-missing && mix local.rebar --force --if-missing

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile Project
        run: mix compile --warnings-as-errors

  Test:
    runs-on: ubuntu-latest

    needs: [Build]

    container:
      image: mikaak/elixir:1.13-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Rebar & Hex
        run: mix local.hex --force --if-missing && mix local.rebar --force --if-missing

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{github.ref}}-deps-build-cache
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Run Tests
        run: mix test

  Credo:
    runs-on: ubuntu-latest

    needs: [Build]

    container:
      image: mikaak/elixir:1.13-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Rebar & Hex
        run: mix local.hex --force --if-missing && mix local.rebar --force --if-missing

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{github.ref}}-deps-build-cache
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Run Credo
        run: mix credo
