name: Test

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deps & Build
        uses: actions/cache@v4
        with:
          key: ${{github.ref}}-deps-build-cache-${{hashFiles('./mix.lock')}}
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.1' # Define the elixir version [required]
          otp-version: '25.1.2' # Define the OTP version [required]

      - name: Install Rebar & Hex
        run: mix local.hex --force --if-missing && mix local.rebar --force --if-missing

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile Project
        run: mix compile --warnings-as-errors

  Test:
    runs-on: ubuntu-latest

    needs: [Build]

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deps & Build
        uses: actions/cache@v4
        with:
          key: ${{github.ref}}-deps-build-cache-${{hashFiles('./mix.lock')}}
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.1' # Define the elixir version [required]
          otp-version: '25.1.2' # Define the OTP version [required]

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test

  Credo:
    runs-on: ubuntu-latest

    needs: [Build]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deps & Build
        uses: actions/cache@v4
        with:
          key: ${{github.ref}}-deps-build-cache-${{hashFiles('./mix.lock')}}
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.1' # Define the elixir version [required]
          otp-version: '25.1.2' # Define the OTP version [required]

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Credo
        run: mix credo

  Coverage:
    runs-on: ubuntu-latest

    needs: [Build]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Deps & Build
        uses: actions/cache@v4
        with:
          key: ${{github.ref}}-deps-build-cache-${{hashFiles('./mix.lock')}}
          path: |
            /github/home/.mix
            ./deps
            ./_build

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.1' # Define the elixir version [required]
          otp-version: '25.1.2' # Define the OTP version [required]

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Coveralls
        run: mix coveralls.json && bash <(curl -s https://codecov.io/bash)

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
